apiVersion: v1
kind: Service
metadata:
    name: "gustavakstesla-c5fe"
    labels:
        app: "gustavakstesla-c5fe"
spec:
    type: LoadBalancer
    ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
      name: http
    selector:
        app: "gustavakstesla-c5fe"