on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: gustavacr01.azurecr.io
        username: ${{ secrets.acr_gustavacr01_username }}
        password: ${{ secrets.acr_gustavacr01_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t gustavacr01.azurecr.io/gustavakstesla:${{ github.sha }}
        docker push gustavacr01.azurecr.io/gustavakstesla:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_gustavakstesla_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep gustav-aks-tesla9688 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace gustav-aks-tesla9688`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: gustav-aks-tesla9688
        container-registry-url: gustavacr01.azurecr.io
        container-registry-username: ${{ secrets.acr_gustavacr01_username }}
        container-registry-password: ${{ secrets.acr_gustavacr01_password }}
        secret-name: gustavakstesdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: gustav-aks-tesla9688
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          gustavacr01.azurecr.io/gustavakstesla:${{ github.sha }}
        imagepullsecrets: |
          gustavakstesdockerauth
